"""Add updated_on to Favorites

Revision ID: 902076f2934f
Revises: ddb91d7bfc78
Create Date: 2023-06-29 20:48:28.914247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902076f2934f'
down_revision = 'ddb91d7bfc78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('updated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'updated_on')
    # ### end Alembic commands ###
