"""Combine Recent and Favorite

Revision ID: a8164161daf2
Revises: 902076f2934f
Create Date: 2023-07-03 15:13:41.039030

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a8164161daf2"
down_revision = "902076f2934f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favorite")
    op.add_column("recent", sa.Column("count", sa.Integer(), nullable=True))
    op.execute("UPDATE recent SET count = 0")
    op.alter_column("recent", "count", nullable=False)
    op.add_column("recent", sa.Column("favorite", sa.Boolean(), nullable=True))
    op.execute("UPDATE recent SET favorite = false")
    op.alter_column("recent", "favorite", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recent", "favorite")
    op.drop_column("recent", "count")
    op.create_table(
        "favorite",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("route_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "added_on",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_on",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["route_id"], ["route.id"], name="favorite_route_id_fkey"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="favorite_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="favorite_pkey"),
        sa.UniqueConstraint("user_id", "route_id", name="uq_user_favorite"),
    )
    # ### end Alembic commands ###
