"""Extend User model

Revision ID: ddb91d7bfc78
Revises: f1a62387cfbb
Create Date: 2023-06-16 15:57:57.597243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb91d7bfc78'
down_revision = 'f1a62387cfbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_bot', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=100), nullable=True))
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'language_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'language_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('user', 'username')
    op.drop_column('user', 'is_bot')
    # ### end Alembic commands ###
